sudo: required
services:
        - docker

before_install:
        - docker build -t oscarlivz/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true oscarlivz/docker-react npm run test -- --coverage

